### PR TITLE
New AutoMergePullRequest action

### PR DESCRIPTION
**Pull request by zeripath**
Signed-off-by: Andrew Thornton <art27@cantab.net>

### CODE REVIEW

**Comment by kolaente** [comment]
So this will re-use the merge email template but change the mail subject to "PR was automerged"?

**Comment by zeripath** [comment]
Yup, but someone could change the email template to add other adjustments based on the ActionType if they needed it.

**Comment by kolaente** [comment]
That sounds a lot cleaner than what I did. Thanks!

**Comment by zeripath** [comment]
np

**Pull request merged**
